from datetime import date

import pandas as pd

# import the backtest library
import optopsy as op

pd.options.display.width = None

vxx_struct = (
    ('symbol', 0),
    ('underlying_price', 1),
    ('option_symbol', 3),
    ('option_type', 5),
    ('expiration', 6),
    ('quote_date', 7),
    ('strike', 8),
    ('bid', 10),
    ('ask', 11),
    ('volume', 12),
    ('oi', 13),
    ('iv', 14),
    ('delta', 15),
    ('gamma', 16),
    ('theta', 17),
    ('vega', 28)
)


def run_strat():
    # fetch the pre-formatted option spread data generated by option
    d = op.get('../data/VXX.csv',
               start=date(2016, 12, 1),  # using a date function here to avoid entering the wrong date format
               end=date(2016, 12, 31),
               struct=vxx_struct
               )

    strategy = op.Strategy('Weekly Long Calls',
                           op.options.Single(option_type='c'), [
                               op.filters.EntryAbsDelta(ideal=0.5, min=0.4, max=0.6),
                               op.filters.EntrySpreadPrice(ideal=1.0, min=0.9, max=1.10),
                               op.filters.EntryDaysToExpiration(ideal=47, min=40, max=52),
                               op.filters.EntryDayOfWeek(ideal=4)
                           ])

    # Create an instance of Optopsy with strategy settings, with default initial capital of $10000
    backtest = op.Optopsy(strategy, d)

    # Run over everything
    results = backtest.run(progress_bar=False)


if __name__ == '__main__':
    run_strat()
