_check_list_type  # unused function (optopsy/checks.py:142)
_trim_cols  # unused function (optopsy/datafeeds.py:43)
drop_nan  # unused variable (optopsy/types.py:45)
_.suppress_debug_info  # unused attribute (optopsy/ui/agent.py:8)
get_data_layer  # unused function (optopsy/ui/app.py:120)
headers  # unused variable (optopsy/ui/app.py:126)
_.input  # unused attribute (optopsy/ui/app.py:292)
_.output  # unused attribute (optopsy/ui/app.py:293)
_.metadata  # unused attribute (optopsy/ui/app.py:295)
_.metadata  # unused attribute (optopsy/ui/app.py:316)
_.language  # unused attribute (optopsy/ui/cli.py:87)
_.confirm_new_chat  # unused attribute (optopsy/ui/cli.py:88)
_.custom_js  # unused attribute (optopsy/ui/cli.py:89)
_.custom_css  # unused attribute (optopsy/ui/cli.py:90)
_handle_preview_data  # unused function (optopsy/ui/tools/_executor.py:115)
_handle_describe_data  # unused function (optopsy/ui/tools/_executor.py:150)
_handle_suggest_strategy_params  # unused function (optopsy/ui/tools/_executor.py:275)
_handle_build_signal  # unused function (optopsy/ui/tools/_executor.py:387)
_handle_preview_signal  # unused function (optopsy/ui/tools/_executor.py:479)
_handle_list_signals  # unused function (optopsy/ui/tools/_executor.py:503)
_handle_fetch_stock_data  # unused function (optopsy/ui/tools/_executor.py:536)
_handle_run_strategy  # unused function (optopsy/ui/tools/_executor.py:599)
_handle_scan_strategies  # unused function (optopsy/ui/tools/_executor.py:733)
_handle_inspect_cache  # unused function (optopsy/ui/tools/_executor.py:856)
_handle_clear_cache  # unused function (optopsy/ui/tools/_executor.py:928)
_handle_simulate  # unused function (optopsy/ui/tools/_executor.py:857)
_handle_get_simulation_trades  # unused function (optopsy/ui/tools/_executor.py:982)
_handle_list_results  # unused function (optopsy/ui/tools/_executor.py:945)
_handle_create_chart  # unused function (optopsy/ui/tools/_executor.py:1269)

# Pydantic model fields and enum members — used at runtime by Pydantic
# Enum members
_.spread  # unused variable (optopsy/ui/tools/_models.py)
_.liquidity  # unused variable (optopsy/ui/tools/_models.py)
_.line  # unused variable (optopsy/ui/tools/_models.py)
_.bar  # unused variable (optopsy/ui/tools/_models.py)
_.scatter  # unused variable (optopsy/ui/tools/_models.py)
_.histogram  # unused variable (optopsy/ui/tools/_models.py)
_.heatmap  # unused variable (optopsy/ui/tools/_models.py)
_.candlestick  # unused variable (optopsy/ui/tools/_models.py)
_.simulation  # unused variable (optopsy/ui/tools/_models.py)
_.stock  # unused variable (optopsy/ui/tools/_models.py)
_.nearest  # unused variable (optopsy/ui/tools/_models.py)
_.highest_premium  # unused variable (optopsy/ui/tools/_models.py)
_.lowest_premium  # unused variable (optopsy/ui/tools/_models.py)
_.first  # unused variable (optopsy/ui/tools/_models.py)
_.and_  # unused variable (optopsy/ui/tools/_models.py)
_.or_  # unused variable (optopsy/ui/tools/_models.py)
# Pydantic model fields
_.entry_signal  # unused variable (optopsy/ui/tools/_models.py)
_.entry_signal_params  # unused variable (optopsy/ui/tools/_models.py)
_.entry_signal_days  # unused variable (optopsy/ui/tools/_models.py)
_.exit_signal  # unused variable (optopsy/ui/tools/_models.py)
_.exit_signal_params  # unused variable (optopsy/ui/tools/_models.py)
_.exit_signal_days  # unused variable (optopsy/ui/tools/_models.py)
_.entry_signal_slot  # unused variable (optopsy/ui/tools/_models.py)
_.exit_signal_slot  # unused variable (optopsy/ui/tools/_models.py)
_.dataset_name  # unused variable (optopsy/ui/tools/_models.py)
_.max_entry_dte_values  # unused variable (optopsy/ui/tools/_models.py)
_.exit_dte_values  # unused variable (optopsy/ui/tools/_models.py)
_.max_otm_pct_values  # unused variable (optopsy/ui/tools/_models.py)
_.max_combinations  # unused variable (optopsy/ui/tools/_models.py)
_.simulation_key  # unused variable (optopsy/ui/tools/_models.py)
_.signal_slot  # unused variable (optopsy/ui/tools/_models.py)
_.mean_return  # unused variable (optopsy/ui/tools/_models.py)
_.win_rate  # unused variable (optopsy/ui/tools/_models.py)
# Pydantic field_validators (called by Pydantic, not directly)
_._validate_signal_name  # unused method (optopsy/ui/tools/_models.py)
_._validate_strategy_name  # unused method (optopsy/ui/tools/_models.py)
_._validate_strategy_names  # unused method (optopsy/ui/tools/_models.py)
# Legacy schema dicts kept for backward compatibility
STRATEGY_PARAMS_SCHEMA  # unused variable (optopsy/ui/tools/_schemas.py)
SIGNAL_PARAMS_SCHEMA  # unused variable (optopsy/ui/tools/_schemas.py)
# cls parameter in Pydantic @classmethod validators
cls  # unused variable (optopsy/ui/tools/_models.py)
